name: CI Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Run tests
        env:
          MONGODB_URI: mongodb://127.0.0.1:27017/serverTestDB
        run: npm test

      - name: Run Postman collection
        env:
          MONGODB_URI: mongodb://127.0.0.1:27017/serverTestDB
        run: npm run ci-test
