name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install cross-env-shell
        run: npm install -g cross-env-shell
      - name: Install Dependencies
        working-directory: server
        run: npm install

  test:
    runs-on: ubuntu-latest
    needs: build  # This job depends on the successful completion of the 'build' job

    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}  # Access secret stored in GitHub Secrets

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v3

      - name: Run Tests
        working-directory: server 
        run: |
          npm run ci-test
          # This will run dropdb.js, start the server, and execute tests using Newman
