name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Clean npm Cache
        run: npm cache clean --force

      - name: Install Dependencies
        working-directory: server
        run: npm install

      - name: Rebuild Native Modules
        working-directory: server
        run: npm rebuild bcrypt

  test:
    runs-on: ubuntu-latest
    needs: build

    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        working-directory: server
        run: npm install

      - name: Rebuild Native Modules
        working-directory: server
        run: npm rebuild bcrypt

      - name: Run Tests
        working-directory: server
        run: npm run ci-test
