name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          cd server
          npm install
        cache:
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          path: server/node_modules/

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    services:
      mongo:
        image: mvertes/alpine-mongo:latest
        ports:
          - 27017:27017
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          cd server
          npm install

      - name: Run Tests
        env:
          MONGODB_URI: "mongodb://localhost:27017/serverTestDB"
        run: |
          cd server
          npm run ci-test
