name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: server/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules

      - name: Install Dependencies
        working-directory: server
        run: npm install

      - name: Rebuild Native Modules
        working-directory: server
        run: npm rebuild bcrypt || echo "Rebuild not required"

  test:
    runs-on: ubuntu-latest
    needs: build

    env:
      MONGODB_URI: mongodb://127.0.0.1:27017/serverTestDB

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Restore Cached Node Modules
        uses: actions/cache@v3
        with:
          path: server/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules

      - name: Install Dependencies
        working-directory: server
        run: npm install

      - name: Kill Existing Processes on Port 3001
        run: |
          sudo lsof -t -i:3001 | xargs -r kill -9 || echo "No processes running on port 3001"

      - name: Start Server
        working-directory: server
        run: |
          npm start &
          sleep 15

      - name: Debug MongoDB and Server Health
        working-directory: server
        run: |
          echo "Testing MongoDB connection..."
          curl http://127.0.0.1:27017 || echo "MongoDB not responding"
          echo "Testing API health..."
          curl http://localhost:3001/api/health || echo "API not responding"

      - name: Run Tests
        working-directory: server
        run: npm run ci-test
